# Generated by Django 5.2.9 on 2025-12-08 20:42

import django.db.models.deletion
import photohostapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=32, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lifetime_days", models.PositiveSmallIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=512)),
                ("file", models.FileField(upload_to=photohostapp.models.upload_to)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="photohostapp.section",
                    ),
                ),
            ],
        ),
    ]
