# Generated by Django 5.2.9 on 2025-12-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photohostapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedfile",
            name="coordinates",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
