# Generated by Django 5.2.9 on 2025-12-09 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photohostapp", "0002_storedfile_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
