# Generated by Django 5.2.9 on 2025-12-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photohostapp", "0003_alter_section_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="keep_original_names",
            field=models.BooleanField(default=False),
        ),
    ]
