# Generated by Django 5.2.9 on 2025-12-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photohostapp", "0004_section_keep_original_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="keep_original_names",
        ),
    ]
