# Generated by Django 5.2.9 on 2025-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photohostapp", "0005_remove_section_keep_original_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="keep_original_filenames",
            field=models.BooleanField(default=False),
        ),
    ]
