# Generated by Django 5.2.9 on 2025-12-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photohostapp", "0006_section_keep_original_filenames"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="batch_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
