# Generated by Django 5.2.9 on 2025-12-25 13:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photohostapp", "0007_section_batch_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ciphertext", models.TextField()),
                ("iv", models.CharField(max_length=64)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("delete_on_read", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
