# Generated by Django 5.2.9 on 2025-12-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photohostapp", "0008_secretnote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SecretNote",
        ),
    ]
