# Generated by Django 5.2.9 on 2025-12-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secret_notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secretnote",
            name="iv",
            field=models.CharField(max_length=24),
        ),
    ]
