# Generated by Django 5.2.9 on 2025-12-25 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secret_notes", "0002_alter_secretnote_iv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secretnote",
            old_name="delete_on_read",
            new_name="delete_after_read",
        ),
        migrations.RenameField(
            model_name="secretnote",
            old_name="is_deleted",
            new_name="is_read",
        ),
        migrations.RemoveField(
            model_name="secretnote",
            name="iv",
        ),
        migrations.RemoveField(
            model_name="secretnote",
            name="password_hash",
        ),
        migrations.RemoveField(
            model_name="secretnote",
            name="read_at",
        ),
        migrations.AlterField(
            model_name="secretnote",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
