# Generated by Django 5.2.9 on 2025-12-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "secret_notes",
            "0003_rename_delete_on_read_secretnote_delete_after_read_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secretnote",
            name="is_read",
        ),
        migrations.AddField(
            model_name="secretnote",
            name="password_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
