# Generated by Django 5.2.9 on 2025-12-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secret_notes", "0004_remove_secretnote_is_read_secretnote_password_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secretnote",
            name="password_hash",
        ),
    ]
