# Generated by Django 5.2.9 on 2025-12-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secret_notes", "0005_remove_secretnote_password_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretnote",
            name="has_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="secretnote",
            name="password_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
